-- Tabella per il catalogo delle carte
CREATE TABLE inventario_asset (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  nome_carta TEXT NOT NULL,
  espansione TEXT,
  condizione TEXT, -- Mint, NM, etc.
  posizione_fisica TEXT, -- Esempio: 'Teca_A_Piano_1'
  prezzo_mercato NUMERIC(10, 2),
  prezzo_negozio NUMERIC(10, 2),
  last_update TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabella per i dati ambientali del negozio a Milano
CREATE TABLE log_ambientale (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  umidita NUMERIC(5, 2),
  temperatura NUMERIC(5, 2),
  zona_id TEXT
);
